### ISSUE TITLE
Errors when attempting to open IPA file

### ISSUE THREAD

**Issue by CamHenlin** [matiassingers/ipa-metadata#4] opened 2015-01-20 20:55 UTC
I'm using OS X 10.10.1, with node v0.10.35 and npm 2.1.18, whenever I try to verify or get the verbose output of an IPA file (on command line or within a node app) I get the following error:

element parse error: Error: attribute equal must after attrName 
@#[line:3,col:33]
Cannot read property 'nodeName' of null

The IPA is able to be installed on devices (via Ad Hoc distribution) without issue, so I am pretty sure it is valid. Any ideas?

**Comment by matiassingers** [comment] 2015-01-21 05:41
@CamHenlin oh I haven't encountered this error before, interesting.

Thanks for your bug report.

I looks like somekind of error in parsing of the `Info.plist` file, but I'm not exactly sure what goes wrong. Is there anyway you could send me the IPA so that I can test on that file?

Otherwise can you try and decompress the IPA file manually:
- Rename from `app.ipa` to `app.zip`, uncompress
- Open the Payload/AppName/
- Attempt to open the `Info.plist` file and see if anything seems out of the ordinary

**Comment by CamHenlin** [comment] 2015-01-21 16:48
Hi @matiassingers thanks for getting back to me so quickly! It actually looks like some variant of this same error is happening with all IPA files that I have tried on this system. I'm wondering if this is some kind of dependent library issue. I'm going to try this out on another machine and see if I have the same issue on these files

**Comment by CamHenlin** [comment] 2015-01-21 17:18
Okay, so I just tried this out on another computer running OS X 10.9.5 and appear to be running into the same set of issues. Also, forgot to mention that unzipping the IPAs and looking at the plists manually works great on all of these. Also, I don't think there's any harm in giving you one of the IPAs that I'm working with since we give it away for free on the app store, here's a download link which I'll pull after you've had a chance to look at the IPA: http://67.189.44.237:9000/HiFi.ipa

**Comment by matiassingers** [comment] 2015-01-21 23:37
@CamHenlin awesome, thanks for the example `ipa` - helped a lot. :+1: 

I figured out what the problem is, the current package that I'm using for parsing the `.plist` file doesn't support parsing of binary `.plist` files. See https://github.com/TooTallNate/plist.js/issues/2
Not sure why I didn't encounter a binary `.plist` file before now.

Let me implement a temporary fix for binary `.plist` parsing, and publish a new version.

**Comment by matiassingers** [comment] 2015-01-22 01:43
@CamHenlin it should be fixed in the latest release([0.6.0](https://github.com/matiassingers/ipa-metadata/releases/tag/0.6.0)).

I tested on the `.ipa` you supplied and it worked, hope it'll work for you as well :wink:

**Closed by matiassingers** 2015-01-22 01:43 UTC
Labels: bug

**Comment by CamHenlin** [comment] 2015-01-22 05:47
Works very well! Thank you!
